version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: nextcloud-db
    restart: always
    volumes:
      - /home/run/srv/nextcloud/pg:/var/lib/postgresql/data
    env_file:
      - .env-db

  app:
    image: nextcloud:16
    container_name: nextcloud-app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - /home/run/srv/nextcloud/app:/var/www/html
    env_file:
      - .env-app
    restart: always

networks:
  default:
    external:
      name: knutech_main
